name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    services:
      docker:
        image: cypress/included:12.0.0
        options: --entrypoint /bin/sh
        ports:
          - 8080:8080
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.1.0'
          

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run
        env:
          VALID_USER: ${{ secrets.VALID_USER }}
          VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
